project: 
  type: website

website:
  title: "2022 ECOSTRESS Cloud Workshop"
  site-url: https://nasa-openscapes.github.io/2022-ECOSTRESS-Cloud-Workshop/
  repo-url: https://github.com/NASA-Openscapes/2022-ECOSTRESS-Cloud-Workshop
  repo-actions: [edit, issue]
  page-navigation: true
  page-footer: "LPDAAC & JPL (2022). 2022 ECOSTRESS Cloud Workshop"
 
  navbar: 
    background: primary
    right: 
      - sidebar:welcome
      - icon: github
        href: https://github.com/NASA-Openscapes/2022-ECOSTRESS-Cloud-Workshop
 
  sidebar:
    - id: welcome
      title: "Menu"
      logo: img/ecostress_lpdaac_image.jpg
      style: "docked"
      collapse-level: 1
      align: left
      contents:
        - text: "Welcome"
          href: index.md
        - text: "Cloud Paradigm"
          href: cloud-paradigm.md
        - text: "Schedule"
          href: schedule.md
        - text: "Prerequisites"
          href: prerequisites.md 
        - section: "Tutorials"
          contents: 
            - tutorials/index.md
 #       - section: "Additional Resources"
  #        contents:
            

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true

#filters:
#  - include-files.lua
#  - quarto